/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ChangePwd: typeof import('./src/components/changePwd/index.vue')['default']
    DelDialogWithNoInfo: typeof import('./src/components/DelModal/delDialogWithNoInfo.vue')['default']
    DelDialogWithTitle: typeof import('./src/components/DelModal/delDialogWithTitle.vue')['default']
    DelModal: typeof import('./src/components/DelModal/index.vue')['default']
    IndexListToInfo: typeof import('./src/components/IndexListToInfo/index.vue')['default']
    Left: typeof import('./src/components/left/index.vue')['default']
    MenuTreeDialog: typeof import('./src/components/menuTreeDialog/index.vue')['default']
    QuillEditor: typeof import('./src/components/QuillEditor/index.vue')['default']
    RegisterDialog: typeof import('./src/components/register/registerDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHeader: typeof import('./src/components/SearchHeader/index.vue')['default']
    UtilsTitle: typeof import('./src/components/UtilsTitle/index.vue')['default']
  }
}
